platform :ios, '8.0'

use_frameworks!

pod 'FBSDKLoginKit'
pod 'PINRemoteImage', '~> 1.1'
pod 'SwiftyJSON', '~> 2.2'

target 'FacebookPhotoKeyboard' do

end

target 'FacebookPhotoKeyboardTests' do

end
