platform :ios, '8.0'

use_frameworks!



target :extension, :exclusive=> true do
    link_with 'FacebookPhotosCustomKeyboard'
    pod 'SwiftyJSON', '~> 2.2'
    pod 'PINRemoteImage', '~> 1.1'
end

target 'FacebookPhotoKeyboard' do

pod 'FBSDKLoginKit'

end

target 'FacebookPhotoKeyboardTests' do

end
